Updated Russian localization
GTNewHorizons/Botania pull request #30
Opened 2023-06-24 16:46 UTC by Pyromanc3r

The mod is now fully translated

2023-07-10 10:05 UTC, repo-alt requested changes
Дочитал до 2500, to be continued...
(В целом по тексту: непоследовательное использование заглавных букв в составных терминах, надо определиться один раз "Лепестковый Аптекарь" или "Лепестковый аптекарь")

2023-07-10 12:58 UTC, repo-alt reviewed
... 3555...

2023-07-10 12:58 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.entropinnyum0=Для получения &4Маны&0 из взрыва, очевидно, потребуется что-нибудь взорвать.<br>Запалив блок &1ТНТ&0 рядом с цветком &1Энтропиннума&0 он поглотит всю энергию взрыва, создав
управление

2023-07-10 12:58 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.tagline.hourglass=Простой таймер, используемый песок
использующий

2023-07-10 12:58 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.manaweave0=&1Манатканная одежда&0 обладает мощными связями с первородной энергией, содержащейся в &4Мане&0. Создание одеяний из ткани, наполненной магией маны, было вопросом времени. Так
управление

2023-07-10 12:58 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.autocraftingHalo0=&1Ореол самосоздания&0 - это ещё один вариант &1Ореола сотворения&0. Помимо выполнения всего, что может сделать первый вариант, этот автоматически попытается выполнить
добыче

2023-07-10 12:58 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.enderHand2=Кроме того, наличие в инвентаре игрока &1Руки Эндера&0 позволяет снабжать &1Жезл обмена&0 предметами из &1Сундука Эндера&0 игрока, что требует повышенных затрат маны по сравне
таки "края" или "эндера" что-то одно

2023-07-10 14:21 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.pavement1=На неё не подскользнётесь
на ней?

2023-07-11 14:02 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +nomobspawnsonthisblock.tip=Мобы не могут спавниться на этом блоке
nomobspawnsonthisblock.tip=Mobs cannot Spawn on this Block
Так "монстры" или "мобы"? 
На счёт "спавниться" согласен. Если адаптируем перевод, а не жёстко используем термин оригинала. Слово "Мобы" хорошо прижилось и его очень часто употребляют игроки. Думаю, что оба варианта правильны.

2023-07-11 14:03 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botaniamisc.lexiconIndex=Индекс Лексикона
Поменял на "оглавление"

2023-07-11 14:05 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botaniamisc.skyblockRangeTooHigh=Диапазон не может превышать 1.000.000 (1 миллион).
Откуда взялось 10 млн? в версии 1.9.23 (перевод делался на эту версию) в файле en_US написано так:
botaniamisc.skyblockRangeTooHigh=Invalid range, can't be higher than 1000000 (1 million).
или уже поменяли?

2023-07-11 14:06 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.nei.petalApothecary=Лепесточный аптекарь
Везде "Лепесточный аптекарь" поменял на "Лепестковый Аптекарь" (название странноватое, как по мне, и как лучше было бы и не знаешь).

2023-07-11 14:06 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.challenge.pureDaisy=Автоматическая чистая маргаритка
Не понял про капс. Это не текст ачивок если что, а описание в книге условий необязательных испытаний

2023-07-11 14:07 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.challenge.apothecaryRefill=Наполнение Лепесточного аптекаря
Тоже самое, что и выше

2023-07-11 14:08 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +item.botania:terraformRod.name=Жезл Терра Фирма
Этот жезл - отсылка к некогда популярному моду https://1710-wiki.terrafirmacraft.com/Main_Page с его особенностью гравитации блоков земли

2023-07-11 14:09 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.flowers11=Подготовка к нечто магическому
Объясняется создание рецепта "цветочного удобрения" при начале работы с ботанией. Помимо красителя из самой ботании можно использовать краситель из базового майна.
Если смущает нумерация строк, то она такая же как в оригинале. Страницы не перепутаны.

2023-07-11 14:09 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.entropinnyum0=Для получения &4Маны&0 из взрыва, очевидно, потребуется что-нибудь взорвать.<br>Запалив блок &1ТНТ&0 рядом с цветком &1Энтропиннума&0 он поглотит всю энергию взрыва, создав
Управление? Не понял

2023-07-11 14:10 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.tagline.hourglass=Простой таймер, используемый песок
Исправил

2023-07-11 14:11 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.manaweave0=&1Манатканная одежда&0 обладает мощными связями с первородной энергией, содержащейся в &4Мане&0. Создание одеяний из ткани, наполненной магией маны, было вопросом времени. Так
Что за управление? 3183 - подправил предложение на "компенсируются бонусом"

2023-07-11 14:11 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.autocraftingHalo0=&1Ореол самосоздания&0 - это ещё один вариант &1Ореола сотворения&0. Помимо выполнения всего, что может сделать первый вариант, этот автоматически попытается выполнить
Исправил

2023-07-11 14:12 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.enderHand2=Кроме того, наличие в инвентаре игрока &1Руки Эндера&0 позволяет снабжать &1Жезл обмена&0 предметами из &1Сундука Эндера&0 игрока, что требует повышенных затрат маны по сравне
"Сундуки Края" заменены на "Сундуки Эндера"

2023-07-11 14:13 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.pavement1=На неё не подскользнётесь
Верно. Исправил "на ней". 
Главный вопрос - как мне теперь внести правки в этот PR? Файл у себя в репозитории я обновил.

2023-07-11 14:14 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botaniamisc.skyblockRangeTooHigh=Диапазон не может превышать 1.000.000 (1 миллион).
Я предположил что исходный текст из оригинальной локализации

2023-07-11 14:16 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.challenge.pureDaisy=Автоматическая чистая маргаритка
Это про непоследовательное использование заглавных, впрочем далее везде в основном не используется капитализация второго слова, так что видимо нужно унифицировать в эту сторону

2023-07-11 14:17 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.flowers11=Подготовка к нечто магическому
"нечто магическому" - управление

2023-07-11 14:19 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.entropinnyum0=Для получения &4Маны&0 из взрыва, очевидно, потребуется что-нибудь взорвать.<br>Запалив блок &1ТНТ&0 рядом с цветком &1Энтропиннума&0 он поглотит всю энергию взрыва, создав
глагольное управление, запалив - поглотит

2023-07-11 14:21 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botaniamisc.dropIkea=&bВыбросив этот предмет разделит его на компоненты
"выбросив - разделит", так как в комментарии - ок

2023-07-11 14:22 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.manaweave0=&1Манатканная одежда&0 обладает мощными связями с первородной энергией, содержащейся в &4Мане&0. Создание одеяний из ткани, наполненной магией маны, было вопросом времени. Так
... но это компенсируется...

2023-07-11 14:23 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.pavement1=На неё не подскользнётесь
просто выкладываешь свою ветку

2023-07-11 14:26 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +nomobspawnsonthisblock.tip=Мобы не могут спавниться на этом блоке
игроки да, но как бы антипогружение
(я не настаиваю, просто бросилось в глаза)

2023-07-11 18:48 UTC, Pyromanc3r commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botaniamisc.dropIkea=&bВыбросив этот предмет разделит его на компоненты
Прошёлся по замечаниям и подправил в разных местах. Нужно ли тут отвечать на каждый комментарий? Или видны все изменения сразу? Тонкостей гитхаба я не знаю

2023-07-12 07:50 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botaniamisc.dropIkea=&bВыбросив кольцо - разделит его на компоненты
Ну как, кто выбросит?, кто разделит? если перевод на русский - пожалей грамматику

2023-07-12 07:51 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botaniamisc.dropIkea=&bВыбросив этот предмет разделит его на компоненты
не нужно

2023-07-12 07:59 UTC, repo-alt commented on src/main/resources/assets/botania/lang/ru_RU.lang
> +botania.page.entropinnyum0=Для получения &4Маны&0 из взрыва, очевидно, потребуется что-нибудь взорвать.<br>Запалив блок &1ТНТ&0 рядом с цветком &1Энтропиннума&0 - поглотит всю энергию взрыва, создав
Запалив блок &1ТНТ&0... (вася выбежал из комнаты)
(если проблему управления не видно  при чтении просто прочитай фразу вслух)

2023-07-16 18:44 UTC, repo-alt approved these changes

2023-07-22 15:05 UTC, merged