Added GoG Skybox support for all dimensions
GTNewHorizons/Botania pull request #42
Opened 2024-02-13 19:19 UTC by Hansbald

- Added a boolean to toggle the feature to the config
- Added an int array to contain the dimension you would like to recieve the Skybox

-Changed the GoG Skybox render check to include above changes

Basically this allows you to display the Garden of Glass in any dimension you wish, instead of just in the overworld. I like to use this to have the skybox in my personal void dimension.

2024-02-16 22:53 UTC, Alastors commented
I mean I personally don't see a problem with it though we'll see what boubou says, he tends to be against this kind of support

2024-02-16 23:14 UTC, boubou19 requested changes

2024-02-16 23:14 UTC, boubou19 commented on src/main/java/vazkii/botania/client/render/world/SkyblockRenderEvents.java
> +				(ConfigHandler.enableFancySkyboxInDimension && (IntStream.of(ConfigHandler.fancySkyboxDimension).anyMatch(x -> x == world.provider.dimensionId))) ||
You should do a set of the dim ids in the config handler, and just check if the set contains the dim ID instead of doing this Stream at each event

2024-05-06 16:26 UTC, combusterf approved these changes

2024-05-06 16:27 UTC, merged