Added warpward as an allowed potion for the blood pendant
GTNewHorizons/Botania pull request #46
Opened 2024-03-06 10:14 UTC by Reflex18

I noticed in botania that there is a number of pedants for potion effects but none for warp ward. However, there are potions in botania for warp ward.

I have set the effect to be allowed to provide another option to deal with warp for players that also invest into the botania side of magic.

This pedant drains a constant amount of mana from the player which requires investment into botania to provide upkeep and does not remove warp from the player at all.

2024-03-06 14:47 UTC, Alastors commented
I’m in a meeting today, but I’ll throughly review this as soon as I’m done <3

2024-03-07 07:01 UTC, combusterf commented
If you look at the code, you'll have noticed that was intentional. Keeping mana stored is easy. An inventory of potions can become a nuisance. This item would pretty much eclipse all other items that provide warp control and thus not be good for balance.

2024-03-07 07:02 UTC, Alastors commented
> Keeping mana stored is easy. An inventory of potions can become a nuisance. This item would pretty much eclipse all other items that provide warp control and thus not be good for balance.

Ehhhhh I disagree based on former descriptions in magic dev, but let me take a look at the code

2024-03-07 07:03 UTC, Alastors commented
Lmfao, yeah probably just needs some tweaking, but expected balancing is around the soul brazier

2024-03-07 07:06 UTC, combusterf requested changes
Balance issues, and strong preference to reject. A config option must be provided at minimum.

2024-03-07 07:07 UTC, Alastors commented
> Balance issues, and strong preference to reject. A config option must be provided at minimum.

You're going to need to be way more specific than just "balancing issues" what are your exact qualms

2024-03-07 07:11 UTC, combusterf commented
> Lmfao, yeah probably just needs some tweaking, but expected balancing is around the soul brazier, which I will note, already does literally this at HV for essentia

Brazier has:
- essentia requirement, i.e. continuous supply of items, i.e. a mob farm
- requires refining and separation and a lot of machinations
- requires centivis, and thus a lot of TC progress and infrastructure
- even then it has a limited range

Pendant just runs off a sun- or coal-charged battery

2024-03-07 07:17 UTC, Alastors commented
> Lmfao, yeah probably just needs some tweaking, but expected balancing is around the soul brazier, which I will note, already does literally this at HV for essentia

Brazier has:
- essentia requirement, i.e. continuous supply of items, i.e. a mob farm
- - not an issue, we literally have a bee that makes essentia now at HV
- requires refining and separation and a lot of machinations
- - incorrect, like I noted above we literally have a bee that produces direct streams of singular essentia now, though basic essentia infrastructure isn't hard at all
- requires centivis, and thus a lot of TC progress and infrastructure
- - cVis requires _**very little**_ infrastructure compared to how little is needed 
- even then it has a limited range
- - nope, this is false, that was fixed a while back

Pendant just runs off a sun- or coal-charged battery
- - soul brazier literally runs off a bee now

Sorry, I didn't mean to edit your comment, mobile's interface is terrible

2024-03-07 07:27 UTC, chochem commented
gotta agree with combusterf (and Abdiel) that A) this looks clearly intentional and B) that mana upkeep is more trivial than soul brazier

2024-03-07 07:32 UTC, Alastors commented
> gotta agree with combusterf (and Abdiel) that A) this looks clearly intentional and B) that mana upkeep is more trivial than soul brazier

So increase the passive cost significantly or add the passive nerfs that Botania is supposed to have I suppose, or both frankly, I don't see why we should pass up on great interactions that will help foster continuing to bring Botania into the fold because of that lmfao, Botania as a whole has continued to struggle to find its place in GTNH because it isn't well integrated and I do fully believe this will help foster that even if only a little more.

Going to point this out though since it's been said repeatedly against me, this is GTNH, the original's author's intention has relatively little impact on the grand scale of things since this isn't their fork.

2024-03-07 09:30 UTC, EnderProyects commented
Could you add a cap to the pendant and if the warp goes over it, it breaks the pendant? Like you can only use it at low warp, but when you have many warp you need to use other machinations

2024-03-12 13:31 UTC, boubou19 commented
@Reflex18 any news on this or should we close this?

2024-03-12 20:30 UTC, Reflex18 commented
> @Reflex18 any news on this or should we close this?

I would say close it as i don't think i have the skill to create the full rework of the pendant that was required to balance it inline with the pack.

2024-03-12 20:31 UTC, closed without merging