Add mana requirements indicator to the mana pool recipes
GTNewHorizons/Botania pull request #52
Opened 2024-05-29 20:09 UTC by socolio

Oh... how to compare recipes with one pixel mana requirements... time to (test) fix
![image](https://github.com/GTNewHorizons/Botania/assets/14280202/8ab93248-675f-4e63-94af-bdc131b3585e)

Tested on one of the latest nightly builds.
Only client-side changes (buts also tested on dedicated server for sabity level stability)

2024-05-29 20:11 UTC, Alastors requested changes
This is an intentional major design decision of Botania and violates our magic integrity policy

2024-05-29 20:13 UTC, Dream-Master commented
I think it can be a nice option to see how much a recipe use instead of go to a wiki / view the code to find out how much it use. Sure we can think of a mechanic to unlock this with some magical research

2024-05-29 20:18 UTC, socolio commented
> I think it can be a nice option to see how much a recipe use instead of go to a wiki / view the code to find out how much it use. Sure we can think of a mechanic to unlock this with some magical research

Current mana bar is accurate enough to meet the needs of the players if mana consumprion is big enought. This change is targeting new players with low level of botania reserach.

2024-05-29 20:19 UTC, Alastors commented
Honestly I'd make the argument that there isn't enough Botania integration to even think about this in that regards 🤷‍♂️

2024-05-29 20:28 UTC, combusterf commented
I'm with Alastors on this one, this was explicitly designed this way by the original author so I don't feel privileged enough to change that.

2024-05-29 20:28 UTC, socolio commented
> Honestly I'd make the argument that there isn't enough Botania integration to even think about this in that regards 🤷‍♂️

In GTNH there exist some sets of recipes where mana consumption fluctuates so enought that it is hard to distinguish real values. of mana requirements

2024-05-29 20:31 UTC, socolio commented
> I'm with Alastors on this one, this was explicitly designed this way by the original author so I don't feel privileged enough to change that.

There is literally no difference between 1000 and 700 mana requirements on low level Botania crafts (according to NEI).

2024-05-29 20:32 UTC, Alastors commented
> > I'm with Alastors on this one, this was explicitly designed this way by the original author so I don't feel privileged enough to change that.
> 
> 
> 
> There is literally no difference between 1000 and 700 mana requirements on low level Botania crafts (according to NEI). That is bad.

🤷‍♂️ it's neither bad nor good, it is simply the mechanic.

2024-05-29 20:33 UTC, Alastors commented
> This is an intentional major design decision of Botania and violates our magic integrity policy

Following up on this, just for case history and all of that, our policy is very explicit in its defense toward maintaining the artistic and mechanical design, here are the policies related to that. 

https://github.com/GTNewHorizons/GTNH-Dev-Doc/blob/master/developer's%20code%20of%20conduct.md

7. Regarding textures within GTNH
- i. Regarding magic textures: within the vision of the modpack, magic is meant to feel, look, and be different from GregTech, any form of GUI update for the sake of (or that would inadvertently bring) consistency with GT GUIs should be rejected.
- ii. Regarding new textures: try to keep textures consistent with the mod/mod group they're being added to.
- iii. Regarding tooltips: reduction is fine when needed, but if there is a specific consistency, try to stay within that.
- iv. Regarding inventory changing: GUIs that shift the colour of the player's internal inventory are allowed as long as its usage is consistent. Examples being: GT's Steam Machines, Magic Bee's Magic Apiary, Railcraft's Coke Oven, etc.

8. The design focus of Magic
As mentioned above, magic within GregTech: New Horizons is meant to have a strong, distinct look, feel, and execution to the typical tech mod in the pack. Thusly, it is of upmost importance that both the artistic and mechanical designs of each mod be treated with the upmost respect and taken into consideration in the creation of new magic content."

Likewise, I think the case history reflects negatively against changes like this: 
 https://github.com/GTNewHorizons/MagicBees/pull/32
 
Going further, despite all of the changes Vazkii made against what his original promises were, the lack of distinct numbers in botania was one of the few things that remained.
 
 # personal note
 
 I do not state this out of malice, nor in attempt to dissuade you from pursuing magic development in general. I am ecstatic to see people passionate about magic in general, and I desperately hope to see you continue this passion in the future. Thank you for your contribution regardless of whether it makes it into the pack or not.

2024-05-29 20:39 UTC, GedeonGrays commented
Just a reminder, Alfheim (Botania addon) already implements numerical mana representation (config option). 
Maybe another reason to add Alfheim to GTNH ¯\_(ツ)_/¯

2024-05-29 20:41 UTC, combusterf requested changes

2024-05-29 20:41 UTC, combusterf commented on src/main/java/vazkii/botania/client/integration/nei/recipe/RecipeHandlerManaPool.java
> +        FontRenderer font = Minecraft.getMinecraft().fontRenderer;
Tab/spaces need to be fixed

2024-05-29 20:41 UTC, combusterf commented on src/main/java/vazkii/botania/client/integration/nei/recipe/RecipeHandlerManaPool.java
> +		font.drawString(manaRequired, 84 - font.getStringWidth(manaRequired) / 2, 71, 0xFF03737F);
To be eligible, this needs a config option that defaults to not showing the numerical mana value

2024-05-29 21:17 UTC, Dream-Master commented
We do not have to adhere to the specifications and standards of the original authors and are free to decide what fits into the GTNH and what does not. Everyone should think freely and break new ground. Thank you.

2024-05-29 21:29 UTC, chochem commented
I am with alastor and combusterf as well. This is antithetical to the basic design principles of botania that makes people like the mod so much.

2024-05-29 21:40 UTC, Connor-Colenso commented
I mean, I would be in favour. I get the original author hated it, but I can't really see a good reason to not allow us to peak into the inner workings so to speak. It just feels like "no because someone 10 years ago said so" which isn't really relevant anymore.

2024-05-29 21:52 UTC, Alastors commented
![image](https://github.com/GTNewHorizons/Botania/assets/78517796/81048764-2f15-4543-8cfc-67aae1851346)
Why don't we just port the book zoom feature, then we stay in line with the original intentions and design

2024-05-29 22:00 UTC, dvdmandt commented
I'm torn. The inability to see exact numbers are indeed thematical and the original design and all that, and it's nice and immersive when you're just doing simple stuff by hand imho, but as soon as you want to really use it for something, you'll likely start looking at wikis, source code or spreadsheets to get the actual numbers anyway. I guess I'm not against the idea of adding some form of item or research (_botanical engineering - the science of mystery?_) or something to unlock this at least.

2024-05-30 17:51 UTC, Dream-Master commented
lets do it like thaumcraft show the full recipe with values when you researched it.

2024-06-05 17:10 UTC, socolio commented
PR may be rejected due to https://github.com/GTNewHorizons/Botania/pull/53

2024-06-05 17:15 UTC, closed without merging

2024-06-05 17:15 UTC, Alastors commented
Closed as per request of the PR owner