various changes
GTNewHorizons/Botania pull request #61
Opened 2024-10-16 09:38 UTC by shadoxxhd

- enchanted soil affects passive generating flowers and Loonium speed, and can be silk touched
- Gourmaryllis now generates mana continously (total amount unchanged)
- Gourmaryllis uses the higher of hunger and saturation of the given food
- Gourmaryllis can consume stacks of items to run for longer at a time, and doesn't consume other items while "eating"
- Pixie ring now provides a pixie chance similar to a single piece of elementium armor (though obviously no armor value)

I'll PR my Loonium blacklist changes if and when I get around to actually linking it to the config file.

2024-10-16 09:43 UTC, chochem requested changes
> Gourmaryllis can consume stacks of items to run for longer at a time, and doesn't consume other items while "eating"

thats a big no.

The other changes are weird too though.

2024-10-16 09:44 UTC, EnderProyects commented
If Loonium is now faster, I think is the time to add it to World Accelerator blacklist...

2024-10-16 10:11 UTC, shadoxxhd commented
The only change to Loonium was to double its mana buffer, so overgrowth seeds correctly cause it to do 2 operations per cycle (at double the mana cost). Are Looniums more expensive to make than finding overgrowth seeds in GTNH? Otherwise, it has no balance implications.

The Gourmaryllis pickup change was mostly to prevent it from "griefing" when eg. mining a chest of food near it. The other changes were mostly aesthetics/preference without strong reasons.

Pixie ring just seemed very weak compared to other Botania rings.

All of these changes were just personal preference; I just figured some of these tweaks might be of interest.

2024-12-21 16:29 UTC, combusterf commented
I agree with chochem, removal of challenge mechanics is a no-go. The rest of the changes seem quite arbitrary and don't sound well thought through.

It would definitely have been more correct to request each change separately.

2025-08-03 09:30 UTC, Nikolay-Sitnikov commented
Almost all the changes here are ill-advised and remove important difficulty mechanics from Botania. There's really nothing useful in this PR & it hasn't received an update in 8 months.

2025-08-03 09:30 UTC, closed without merging